import type { Metadata } from "next";

import "./globals.css";

import Headers from '@/components/Header'
import { Footer } from "@/components/Footer";
import {CallToAction} from '@/components/CTA'
import { FloatingIcons } from '@/components/Floating-icons'
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Headers/>
        <FloatingIcons/>
        {children}
        <CallToAction/>
        <Footer/>
      </body>
    </html>
  );
}
